DROP TABLE IF EXISTS `progression_item_template`;
CREATE TABLE `progression_item_template` (
    `entry` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    `patch` INT(2) UNSIGNED NOT NULL DEFAULT '0',
    `class` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `subclass` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `SoundOverrideSubclass` TINYINT(4) NOT NULL DEFAULT -1,
    `name` VARCHAR(255) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
    `displayid` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    `Quality` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `Flags` INT(10) UNSIGNED NOT NULL DEFAULT '0',
    `FlagsExtra` INT(10) UNSIGNED NOT NULL DEFAULT '0',
    `BuyCount` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
    `BuyPrice` BIGINT(20) NOT NULL DEFAULT '0',
    `SellPrice` INT(10) UNSIGNED NOT NULL DEFAULT '0',
    `InventoryType` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `AllowableClass` INT(11) NOT NULL DEFAULT -1,
    `AllowableRace` INT(11) NOT NULL DEFAULT -1,
    `ItemLevel` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `RequiredLevel` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `RequiredSkill` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `RequiredSkillRank` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `requiredspell` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    `requiredhonorrank` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    `RequiredCityRank` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    `RequiredReputationFaction` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `RequiredReputationRank` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `maxcount` INT(11) NOT NULL DEFAULT '0',
    `stackable` INT(11) NULL DEFAULT '1',
    `ContainerSlots` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `StatsCount` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `stat_type1` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `stat_value1` SMALLINT(6) NOT NULL DEFAULT '0',
    `stat_type2` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `stat_value2` SMALLINT(6) NOT NULL DEFAULT '0',
    `stat_type3` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `stat_value3` SMALLINT(6) NOT NULL DEFAULT '0',
    `stat_type4` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `stat_value4` SMALLINT(6) NOT NULL DEFAULT '0',
    `stat_type5` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `stat_value5` SMALLINT(6) NOT NULL DEFAULT '0',
    `stat_type6` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `stat_value6` SMALLINT(6) NOT NULL DEFAULT '0',
    `stat_type7` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `stat_value7` SMALLINT(6) NOT NULL DEFAULT '0',
    `stat_type8` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `stat_value8` SMALLINT(6) NOT NULL DEFAULT '0',
    `stat_type9` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `stat_value9` SMALLINT(6) NOT NULL DEFAULT '0',
    `stat_type10` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `stat_value10` SMALLINT(6) NOT NULL DEFAULT '0',
    `ScalingStatDistribution` SMALLINT(6) NOT NULL DEFAULT '0',
    `ScalingStatValue` INT(10) UNSIGNED NOT NULL DEFAULT '0',
    `dmg_min1` FLOAT NOT NULL DEFAULT '0',
    `dmg_max1` FLOAT NOT NULL DEFAULT '0',
    `dmg_type1` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `dmg_min2` FLOAT NOT NULL DEFAULT '0',
    `dmg_max2` FLOAT NOT NULL DEFAULT '0',
    `dmg_type2` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `armor` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `holy_res` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `fire_res` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `nature_res` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `frost_res` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `shadow_res` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `arcane_res` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `delay` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '1000',
    `ammo_type` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `RangedModRange` FLOAT NOT NULL DEFAULT '0',
    `spellid_1` MEDIUMINT(9) NOT NULL DEFAULT '0',
    `spelltrigger_1` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `spellcharges_1` SMALLINT(6) NOT NULL DEFAULT '0',
    `spellppmRate_1` FLOAT NOT NULL DEFAULT '0',
    `spellcooldown_1` INT(11) NOT NULL DEFAULT -1,
    `spellcategory_1` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `spellcategorycooldown_1` INT(11) NOT NULL DEFAULT -1,
    `spellid_2` MEDIUMINT(9) NOT NULL DEFAULT '0',
    `spelltrigger_2` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `spellcharges_2` SMALLINT(6) NOT NULL DEFAULT '0',
    `spellppmRate_2` FLOAT NOT NULL DEFAULT '0',
    `spellcooldown_2` INT(11) NOT NULL DEFAULT -1,
    `spellcategory_2` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `spellcategorycooldown_2` INT(11) NOT NULL DEFAULT -1,
    `spellid_3` MEDIUMINT(9) NOT NULL DEFAULT '0',
    `spelltrigger_3` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `spellcharges_3` SMALLINT(6) NOT NULL DEFAULT '0',
    `spellppmRate_3` FLOAT NOT NULL DEFAULT '0',
    `spellcooldown_3` INT(11) NOT NULL DEFAULT -1,
    `spellcategory_3` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `spellcategorycooldown_3` INT(11) NOT NULL DEFAULT -1,
    `spellid_4` MEDIUMINT(9) NOT NULL DEFAULT '0',
    `spelltrigger_4` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `spellcharges_4` SMALLINT(6) NOT NULL DEFAULT '0',
    `spellppmRate_4` FLOAT NOT NULL DEFAULT '0',
    `spellcooldown_4` INT(11) NOT NULL DEFAULT -1,
    `spellcategory_4` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `spellcategorycooldown_4` INT(11) NOT NULL DEFAULT -1,
    `spellid_5` MEDIUMINT(9) NOT NULL DEFAULT '0',
    `spelltrigger_5` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `spellcharges_5` SMALLINT(6) NOT NULL DEFAULT '0',
    `spellppmRate_5` FLOAT NOT NULL DEFAULT '0',
    `spellcooldown_5` INT(11) NOT NULL DEFAULT -1,
    `spellcategory_5` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `spellcategorycooldown_5` INT(11) NOT NULL DEFAULT -1,
    `bonding` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `description` VARCHAR(255) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
    `PageText` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    `LanguageID` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `PageMaterial` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `startquest` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    `lockid` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    `Material` TINYINT(4) NOT NULL DEFAULT '0',
    `sheath` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `RandomProperty` MEDIUMINT(9) NOT NULL DEFAULT '0',
    `RandomSuffix` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    `block` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    `itemset` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    `MaxDurability` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `area` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    `Map` SMALLINT(6) NOT NULL DEFAULT '0',
    `BagFamily` MEDIUMINT(9) NOT NULL DEFAULT '0',
    `TotemCategory` MEDIUMINT(9) NOT NULL DEFAULT '0',
    `socketColor_1` TINYINT(4) NOT NULL DEFAULT '0',
    `socketContent_1` MEDIUMINT(9) NOT NULL DEFAULT '0',
    `socketColor_2` TINYINT(4) NOT NULL DEFAULT '0',
    `socketContent_2` MEDIUMINT(9) NOT NULL DEFAULT '0',
    `socketColor_3` TINYINT(4) NOT NULL DEFAULT '0',
    `socketContent_3` MEDIUMINT(9) NOT NULL DEFAULT '0',
    `socketBonus` MEDIUMINT(9) NOT NULL DEFAULT '0',
    `GemProperties` MEDIUMINT(9) NOT NULL DEFAULT '0',
    `RequiredDisenchantSkill` SMALLINT(6) NOT NULL DEFAULT -1,
    `ArmorDamageModifier` FLOAT NOT NULL DEFAULT '0',
    `duration` INT(10) UNSIGNED NOT NULL DEFAULT '0',
    `ItemLimitCategory` SMALLINT(6) NOT NULL DEFAULT '0',
    `HolidayId` INT(10) UNSIGNED NOT NULL DEFAULT '0',
    `ScriptName` VARCHAR(64) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
    `DisenchantID` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    `FoodType` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `minMoneyLoot` INT(10) UNSIGNED NOT NULL DEFAULT '0',
    `maxMoneyLoot` INT(10) UNSIGNED NOT NULL DEFAULT '0',
    `flagsCustom` INT(10) UNSIGNED NOT NULL DEFAULT '0',
    `VerifiedBuild` SMALLINT(6) NULL DEFAULT '0',
    PRIMARY KEY (`entry`, `patch`) USING BTREE,
    INDEX `idx_name` (`name`(250)) USING BTREE,
    INDEX `items_index` (`class`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;
